###데이터셋 준비

In [ ]:
import pandas as pd

In [ ]:
# df1 = pd.read_csv('/content/drive/MyDrive/mingyu/크롤링데이터(casenote)/사기결과.csv')
# df2 = pd.read_csv('/content/drive/MyDrive/mingyu/크롤링데이터(casenote)/이혼결과.csv')
# df3 = pd.read_csv('/content/drive/MyDrive/mingyu/크롤링데이터(casenote)/의료사고결과.csv')
# df4 = pd.read_csv('/content/drive/MyDrive/mingyu/크롤링데이터(casenote)/성추행결과.csv')
# df5 = pd.read_csv('/content/drive/MyDrive/mingyu/크롤링데이터(casenote)/방화결과.csv')
# df6 = pd.read_csv('/content/drive/MyDrive/mingyu/크롤링데이터(casenote)/모욕결과.csv')
# df7 = pd.read_csv('/content/drive/MyDrive/mingyu/크롤링데이터(casenote)/명예훼손결과.csv')
# df8 = pd.read_csv('/content/drive/MyDrive/mingyu/크롤링데이터(casenote)/마약결과.csv')

# df1 = pd.DataFrame(df1)
# df2 = pd.DataFrame(df2)
# df3 = pd.DataFrame(df3)
# df4 = pd.DataFrame(df4)
# df5 = pd.DataFrame(df5)
# df6 = pd.DataFrame(df6)
# df7 = pd.DataFrame(df7)
# df8 = pd.DataFrame(df8)

In [ ]:
# df = pd.concat([df1,df2, df3, df4, df5, df6, df7, df8], ignore_index=True)

In [ ]:
df1 = pd.read_pickle('/content/drive/MyDrive/miri/df_example2.pickle')
txt = df1['전처리'][0]

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/mingyu/가공데이터/fine_tune_sent.csv')
df2['sent1'][0]

' 청구인들은 산부인과를 진료과목으로 의원 또는 병원을 개설한 보건의료기관개설자들이다 '

In [ ]:
text = ' 처분 의 경위 원고는 피고에게 한의사 에 대해 의료사고 손해배상 청구를 제기하였고 법원에서 조정이 성립되었으나 손해배상의무자인 이 경제적으로 어려운 상황에 처하여 손해배상금을 지급받지 못하고 있다 는 이유로 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 조 항 및 같은 법 시행령 제 조에 따라 위 조정조서상의 손해배상금 원금 원의 대불을 청구하였다 '
text

' 처분 의 경위 원고는 피고에게 한의사 에 대해 의료사고 손해배상 청구를 제기하였고 법원에서 조정이 성립되었으나 손해배상의무자인 이 경제적으로 어려운 상황에 처하여 손해배상금을 지급받지 못하고 있다 는 이유로 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 조 항 및 같은 법 시행령 제 조에 따라 위 조정조서상의 손해배상금 원금 원의 대불을 청구하였다 '

In [ ]:
preprocess(text)

' 처분 경위 원고는 피고에게 한의사 대해 의료사고 손해배상 청구를 제기하였고 법원에서 조정이 성립되었으나 손해배상의무자인 경제적으로 어려운 상황에 처하여 손해배상금을 지급받지 못하고 있다 이유로 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 항 및 같은 시행령 조에 따라 위 조정조서상의 손해배상금 원금 원의 대불을 청구하였다 '

###의료사고 결과 전처리하기

In [ ]:
df3 = pd.read_csv('/content/drive/MyDrive/mingyu/크롤링데이터(casenote)/의료사고결과.csv')
df3 = pd.DataFrame(df3)
df3

이유  \
0    \n1. 사건개요\n청구인들은 산부인과를 진료과목으로 의원 또는 병원을 개설한 보건...   
1    \n1. 사건개요\n가. 청구인들은 의원급 의료기관 개설자로서 ‘의료사고 피해구제 ...   
2    \n1. 사건개요\n가.청구인은 ‘○○병원’을 운영하는 정신과 전문의이다.\n나.청...   
3    \n1. 사건개요\n가. 제청신청인들은 의사로서 ‘의료사고 피해구제 및 의료분쟁 조...   
4    \n   1. 사건개요\n   가. 2011. 4. 7. 제정된 ‘의료사고 피해구제...   
..                                                 ...   
195  \n1. 인정 사실\n 가. 당사자들의 관계\n   1) 피고 E은 울산 남구 H에...   
196  \n  1. 피고 \n        1 주식회사에 대한 청구에 관한 판단\n    ...   
197  \n    의료사고에  있어서  의사의  과실을 인정하기  위해서는 의사가 결과발생...   
198  \nl. 기초사실\n 가. 망 A의 수술 및 장애 발생 경과\n  1) 망 A(D생...   
199  \n1. 기초사실\n 가. 이 사건 각 보험계약의 체결\n  1) 원고는 피고와 2...   

                                                 참조 조문  \
0                                              no data   
1                                              no data   
2    의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률(2018. 12. 11. 법률 ...   
3    \n의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률(2011. 4. 7. 법률 ...   
4                                              no data   
..                                                 ...   
195  [1] 헌법 제12조 제1항, 형법 제1조 제1항, 의료법 제1조, 제2조 제1항,...   
196                                            no data   
197                                            no data   
198                                            no data   
199                                            no data   

                                                    요지  \
0                                              no data   
1                                              no data   
2    환자의 사망이라는 중한 결과가 발생한 경우 환자 측으로서는 피해를 신속·공정하게 구...   
3                                              no data   
4    \n   가. 의료분쟁조정법 제47조 제1항은 손해배상금 대불제도의 기본적인 사항에...   
..                                                 ...   
195                                            no data   
196  \n가. 피해자가 1차사고(산재사고)로 인하여 상해를 입고 입원치료 중 2차사고(의...   
197                                            no data   
198                                            no data   
199                                            no data   

                                                 참조 판례  
0                                               nodata  
1                                               nodata  
2              헌재 2014. 4. 24. 2013헌가4, 판례집 26-1상, 587  
3                                               nodata  
4    가. 헌재 2008. 2. 28. 2006헌바70, 판례집 20-1, 250 / 나...  
..                                                 ...  
195                                             nodata  
196  \n\n대법원 1979.4.24. 선고 79다156 판결(요민I 민법 제763조(3...  
197                                             nodata  
198                                             nodata  
199                                             nodata  

[200 rows x 4 columns]

###PreProcessing

In [ ]:
import re

In [ ]:
stopword = open('/content/drive/MyDrive/miri/law_stopwords.txt', 'rt').read()
stopwords = stopword.split('\n')
print(stopwords)

FileNotFoundError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
def preprocess(sen):

  #한글과 구두점을 제외하고 '가,나,다,라,마,바,사,아' 문자와 특수문자, 숫자 제거
  sen = re.sub(r'\n', r' ', sen)
  sen = re.sub(r'[0-9]+건.+? ', r' ', sen)
  sen = re.sub(r'[0-9]+\.', r' ', sen)
  sen = re.sub(r'[0-9].', r' ', sen)
  sen = re.sub(r'\([^)]*\)', r'', sen)
  sen = re.sub(r' [가나다라마바사아자차]\s?\.', r'', sen)
  sen = re.sub(r'[가-힣]○○', r'', sen)
  sen = re.sub(r'[^ㄱ-ㅎ가-힣\.]+', r' ', sen)
  sen = re.sub(r' [가나다라마바사아자차] ', r' ', sen)
  for stop in stopwords:
    sen = re.sub(stop, r' ', sen)
  
  #단어와 구두점, 쉼표 사이에 공백
  sen = re.sub(r'([\.])', r' \1', sen)

  #다수 개 공백을 하나의 공백으로 치환
  sen = re.sub(r"\s+", " ", sen)

  s_split = sen.split('.')

  return_s = [s for s in s_split if len(s)>3]

  return '.'.join(return_s)

In [ ]:
text = df3['이유']
text

0      \n1. 사건개요\n청구인들은 산부인과를 진료과목으로 의원 또는 병원을 개설한 보건...
1      \n1. 사건개요\n가. 청구인들은 의원급 의료기관 개설자로서 ‘의료사고 피해구제 ...
2      \n1. 사건개요\n가.청구인은 ‘○○병원’을 운영하는 정신과 전문의이다.\n나.청...
3      \n1. 사건개요\n가. 제청신청인들은 의사로서 ‘의료사고 피해구제 및 의료분쟁 조...
4      \n   1. 사건개요\n   가. 2011. 4. 7. 제정된 ‘의료사고 피해구제...
                             ...                        
195    \n1. 인정 사실\n 가. 당사자들의 관계\n   1) 피고 E은 울산 남구 H에...
196    \n  1. 피고 \n        1 주식회사에 대한 청구에 관한 판단\n    ...
197    \n    의료사고에  있어서  의사의  과실을 인정하기  위해서는 의사가 결과발생...
198    \nl. 기초사실\n 가. 망 A의 수술 및 장애 발생 경과\n  1) 망 A(D생...
199    \n1. 기초사실\n 가. 이 사건 각 보험계약의 체결\n  1) 원고는 피고와 2...
Name: 이유, Length: 200, dtype: object

In [ ]:
df3['전처리'] = text.apply(lambda x : preprocess(x))

In [ ]:
df = df3[['이유','전처리']]

In [ ]:
df['pre_split'][0]

In [ ]:
df['pre_split'] = df['전처리'].apply(lambda x : x.split('.'))
df['pre_split'][0]

<ipython-input-57-6f06a073bb92>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pre_split'] = df['전처리'].apply(lambda x : x.split('.'))


[' 청구인들은 산부인과를 진료과목으로 의원 또는 병원을 개설한 보건의료기관개설자들이다 ',
 ' 청구인들은 분만에 따른 일정한 의료사고로 발생한 피해를 보상하기 위한 사업에 드는 비용의 보건의료기관개설자 중 분만 실적이 있는 자가 부담하고 보건의료기관개설자가 분담해야 할 금액은 보건복지부장관이 정하는 방법에 따라 한국의료분쟁조정중재원장이 부과하도록 규정하고 있는 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 및 같은 시행령 조로 인하여 청구인들의 재산권 평등권 등이 침해되었다고 주장하면서 사건 헌법소원 심판을 청구하였다 ',
 ' 심판대상 청구인들은 사건 헌법소원 심판을 청구하면서 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 및 같은 시행령 전부를 심판대상조항으로 삼고 있다 ',
 ' 그러나 이들 조항 중에서 청구인들이 주장하는 기본권 침해와 관련된 것은 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 중 따른 보건의료기관개설자의 범위 보상재원의 분담비율 부분과 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 시행령 제 뿐이므로 사건 심판대상은 법령조항들이 청구인들의 기본권을 침해하는지 여부이다 ',
 ' 심판대상조항 및 관련조항의 내용은 다음과 같다 ',
 ' 심판대상조항 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 조정중재원은 따른 의료사고 보상사업에 드는 비용의 일부를 보건의료기관개설자 등 대통령령으로 정하는 자에게 분담하게 할 수 있다 ',
 ' 따른 의료사고보상심의위원회의 구성 및 운영 따른 보건의료기관개설자의 범위 보상재원의 분담비율 보상의 범위 보상금의 지급기준 및 절차 등에 관하여 필요한 사항은 대통령령으로 정한다 ',
 ' 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 시행령 따른 의료사고 보상사업에 드는 비용은 다음 구분에 따라 부담한다 ',
 ' 보건의료기관개설자 중 분만 실적이 있는 제 따라 보건의료기관개설자가 분담해야 할 금액은 보건복지부장관이 정하는 방법에 따라 원장이 부과한다 ',
 ' 의

In [ ]:
sentence = []
num_sen = []

for i, pre in enumerate(df['pre_split']):#해당 index, pre_split의 한 문장
  sentence.extend(pre)
  # print(len(pre))
  num_sen.extend([i] * len(pre))
  # print(num_sen)
len(sentence), len(num_sen)

(5547, 5547)

In [ ]:
df_new = pd.DataFrame(zip(sentence, num_sen), columns = ('sentence','pan_num'))
df_new.to_csv('문장5500.csv', encoding='utf-8', index=False)

In [ ]:
df['pre_split'] = df['전처리'].apply(lambda x : x.split('.'))
df

KeyError: ignored

In [ ]:
df['pre_split'][0]

[' 청구인들은 산부인과를 진료과목으로 의원 또는 병원을 개설한 보건의료기관개설자들이다 ',
 ' 청구인들은 분만에 따른 일정한 의료사고로 발생한 피해를 보상하기 위한 사업에 드는 비용의 보건의료기관개설자 중 분만 실적이 있는 자가 부담하고 보건의료기관개설자가 분담해야 할 금액은 보건복지부장관이 정하는 방법에 따라 한국의료분쟁조정중재원장이 부과하도록 규정하고 있는 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 및 같은 시행령 조로 인하여 청구인들의 재산권 평등권 등이 침해되었다고 주장하면서 사건 헌법소원 심판을 청구하였다 ',
 ' 심판대상 청구인들은 사건 헌법소원 심판을 청구하면서 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 및 같은 시행령 전부를 심판대상조항으로 삼고 있다 ',
 ' 그러나 이들 조항 중에서 청구인들이 주장하는 기본권 침해와 관련된 것은 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 중 따른 보건의료기관개설자의 범위 보상재원의 분담비율 부분과 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 시행령 제 뿐이므로 사건 심판대상은 법령조항들이 청구인들의 기본권을 침해하는지 여부이다 ',
 ' 심판대상조항 및 관련조항의 내용은 다음과 같다 ',
 ' 심판대상조항 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 조정중재원은 따른 의료사고 보상사업에 드는 비용의 일부를 보건의료기관개설자 등 대통령령으로 정하는 자에게 분담하게 할 수 있다 ',
 ' 따른 의료사고보상심의위원회의 구성 및 운영 따른 보건의료기관개설자의 범위 보상재원의 분담비율 보상의 범위 보상금의 지급기준 및 절차 등에 관하여 필요한 사항은 대통령령으로 정한다 ',
 ' 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 시행령 따른 의료사고 보상사업에 드는 비용은 다음 구분에 따라 부담한다 ',
 ' 보건의료기관개설자 중 분만 실적이 있는 제 따라 보건의료기관개설자가 분담해야 할 금액은 보건복지부장관이 정하는 방법에 따라 원장이 부과한다 ',
 ' 의

In [ ]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 58.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 68.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 20.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 53.4 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=ebf46a9b8c2d2ffcbf7817cebfa2d4ca7b456c114ec6cb6b6a3e97662c0571fb
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer
sentences = ["안녕하세요?", "한국어 문장 임베딩을 위한 버트 모델입니다."]

model = SentenceTransformer('jhgan/ko-sroberta-multitask')
embeddings = model.encode(sentences)
print(embeddings)
print(embeddings.shape)


In [ ]:
NUM_SAMPLES = 200
from tqdm import tqdm
sen_emb_vec = []
for i in tqdm(range(NUM_SAMPLES)):
  sen_emb_vec.append(model.encode(df['전처리'][i]))
sen_emb_vec

In [ ]:
df['sen_emb_vec'] = sen_emb_vec

<ipython-input-68-e139c5af800b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sen_emb_vec'] = sen_emb_vec


In [ ]:
df

이유  \
0    \n1. 사건개요\n청구인들은 산부인과를 진료과목으로 의원 또는 병원을 개설한 보건...   
1    \n1. 사건개요\n가. 청구인들은 의원급 의료기관 개설자로서 ‘의료사고 피해구제 ...   
2    \n1. 사건개요\n가.청구인은 ‘○○병원’을 운영하는 정신과 전문의이다.\n나.청...   
3    \n1. 사건개요\n가. 제청신청인들은 의사로서 ‘의료사고 피해구제 및 의료분쟁 조...   
4    \n   1. 사건개요\n   가. 2011. 4. 7. 제정된 ‘의료사고 피해구제...   
..                                                 ...   
195  \n1. 인정 사실\n 가. 당사자들의 관계\n   1) 피고 E은 울산 남구 H에...   
196  \n  1. 피고 \n        1 주식회사에 대한 청구에 관한 판단\n    ...   
197  \n    의료사고에  있어서  의사의  과실을 인정하기  위해서는 의사가 결과발생...   
198  \nl. 기초사실\n 가. 망 A의 수술 및 장애 발생 경과\n  1) 망 A(D생...   
199  \n1. 기초사실\n 가. 이 사건 각 보험계약의 체결\n  1) 원고는 피고와 2...   

                                                   전처리  \
0     청구인들은 산부인과를 진료과목으로 의원 또는 병원을 개설한 보건의료기관개설자들이다...   
1     청구인들은 의원급 의료기관 개설자로서 의료사고 피해구제 및 의료분쟁 조정 등에 관...   
2     사건개요청구인은 병원 운영하는 정신과 전문의이다 .청구 외 등은 청구 외 망 자녀...   
3     제청신청인들은 의사로서 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 보...   
4     제정된 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 의료사고 피해자가 한국...   
..                                                 ...   
195   인정 사실 당사자들의 관계 피고 울산 남구 에서 병원을 운영하는 의사이고 피고 병...   
196   피고 주식회사에 대한 청구에 관한 판단 손해배상책임의 발생 각 성립에 다툼이 없는...   
197   의료사고에 있어서 의사의 과실을 인정하기 위해서는 의사가 결과발생을 예견할 수 있...   
198   망 수술 및 장애 발생 경과 망 허리통증 등을 이유로 피고가 운영하는 고려대학교 ...   
199   사건 각 보험계약의 체결 원고는 피고와 별지 목록 기재 보험계약을 별지 목록 기재...   

                                             pre_split  \
0    [ 청구인들은 산부인과를 진료과목으로 의원 또는 병원을 개설한 보건의료기관개설자들이...   
1    [ 청구인들은 의원급 의료기관 개설자로서 의료사고 피해구제 및 의료분쟁 조정 등에 ...   
2    [ 사건개요청구인은 병원 운영하는 정신과 전문의이다 , 청구 외 등은 청구 외 망 ...   
3    [ 제청신청인들은 의사로서 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 제 ...   
4    [ 제정된 의료사고 피해구제 및 의료분쟁 조정 등에 관한 법률 의료사고 피해자가 한...   
..                                                 ...   
195  [ 인정 사실 당사자들의 관계 피고 울산 남구 에서 병원을 운영하는 의사이고 피고 ...   
196  [ 피고 주식회사에 대한 청구에 관한 판단 손해배상책임의 발생 각 성립에 다툼이 없...   
197  [ 의료사고에 있어서 의사의 과실을 인정하기 위해서는 의사가 결과발생을 예견할 수 ...   
198  [ 망 수술 및 장애 발생 경과 망 허리통증 등을 이유로 피고가 운영하는 고려대학교...   
199  [ 사건 각 보험계약의 체결 원고는 피고와 별지 목록 기재 보험계약을 별지 목록 기...   

                                           sen_emb_vec  
0    [-0.22695284, -0.6587131, -0.23290378, -0.5395...  
1    [-0.31849205, -0.5812987, 0.29699665, -0.49497...  
2    [-0.63337743, -0.47198412, 0.32942045, -0.1761...  
3    [-0.11402394, -0.3654193, 0.19287068, -0.23131...  
4    [-0.20440166, -0.25814512, 0.3448158, -0.13717...  
..                                                 ...  
195  [-0.6002624, 0.037281655, -0.07159034, -0.0062...  
196  [-0.16323733, -0.31358194, 0.0742475, -0.40339...  
197  [-0.8337102, 0.300156, -0.032296557, -0.395208...  
198  [-0.6659304, 0.15295804, 0.48748684, 0.1093464...  
199  [-0.42657968, -0.21550909, 0.7242929, -0.25939...  

[200 rows x 4 columns]

In [ ]:
df_new.to_pickle('문장임베딩.pickle')

In [ ]:
df = pd.read_pickle('/content/drive/MyDrive/miri/문장임베딩.pickle')
df

sentence  pan_num  \
0        청구인들은 산부인과를 진료과목으로 의원 또는 병원을 개설한 보건의료기관개설자들이다         0   
1      청구인들은 분만에 따른 일정한 의료사고로 발생한 피해를 보상하기 위한 사업에 드는...        0   
2      심판대상 청구인들은 사건 헌법소원 심판을 청구하면서 의료사고 피해구제 및 의료분쟁...        0   
3      그러나 이들 조항 중에서 청구인들이 주장하는 기본권 침해와 관련된 것은 의료사고 ...        0   
4                            심판대상조항 및 관련조항의 내용은 다음과 같다         0   
...                                                 ...      ...   
5542   한편 피고가 경 원고에게 사건 보험사고로 인한 보험금을 청구하였음은 앞서 본 바와...      199   
5543   그러나 위와 같은 보험금청구는 시효중단 사유 중 최고 해당하여 그로부터 월 내에 ...      199   
5544              따라서 피고의 위 소멸시효 중단 주장은 어느 모로 보나 이유 없다       199   
5545   그러므로 사건 보험사고와 관련하여 사건 각 보험계약에 기한 원고의 피고에 대한 상...      199   
5546   그렇다면 원고의 사건 본소청구는 이유 있으므로 이를 인용하고 피고의 사건 반소청구...      199   

                                    sentence_emb_vector  
0     [-0.2192789, -0.6166278, -0.24053057, -0.69428...  
1     [-0.3239567, -0.5662372, -0.107696, -0.3873411...  
2     [-0.5495779, -0.558125, 0.09490602, -0.5618078...  
3     [-0.27730063, -0.3266754, 0.22384566, -0.58724...  
4     [0.014165878, -0.06559759, 0.2303777, -0.17142...  
...                                                 ...  
5542  [-0.2279148, -0.41516253, 0.6987348, -0.068809...  
5543  [-0.021511555, -0.057465862, 0.72078145, -0.32...  
5544  [-0.14008988, -0.6448783, 0.6140536, -0.033696...  
5545  [-0.39172632, -0.2762254, 0.61632663, -0.52536...  
5546  [-0.11227926, -0.4777575, 0.41085032, -0.63251...  

[5547 rows x 3 columns]

In [ ]:
df['pan_emb_list'] = pan_emb_list

<ipython-input-21-f898582002ef>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pan_emb_list'] = pan_emb_list


In [ ]:
df['pan_emb_list'].to_csv('pan_emb_list.csv', index=False, encoding='utf-8')

In [ ]:
pd.read_csv('/content/drive/MyDrive/miri/pan_emb_list.csv')

Unnamed: 0                                       pan_emb_list
0             0  [[-0.21927908 -0.6166278  -0.2405303  ...  0.1...
1             1  [[-0.17839883 -0.6009488  -0.03735216 ...  0.1...
2             2  [[-8.39957297e-01 -1.12983167e-01  2.74095476e...
3             3  [[-0.08149841 -0.36784548  0.20679975 ... -0.0...
4             4  [[-0.25407675 -0.29219586  0.16809893 ...  0.1...
..          ...                                                ...
195         195  [[-0.22828993 -0.08001366  0.04552349 ... -0.1...
196         196  [[-0.16323727 -0.3135817   0.07424769 ...  0.2...
197         197  [[-0.8337101   0.30015603 -0.03229628 ...  0.4...
198         198  [[-0.5869843   0.26869848  0.33931434 ... -0.4...
199         199  [[-0.17777812 -0.30242884  0.78649    ...  0.2...

[200 rows x 2 columns]

In [ ]:
 lawtalk = '''안과 라식수술중 의료사고 입니다.
안과에서 시력교정수술 진행 가능한지 관련하여 검사를 받고. 수술가능하다는 소견을받고 라식수술진행  (진행 당시 수술동의서는 작성하지 않았음)
오른쪽 눈부터 수술하였으며 각막 절삭 중 각막을 깊게 자르는 의료사고 발생하였고 각막열공이 되어.수술을 진행하던 원장님이 바로 수술 중단 후 대학 병원으로 이송하여 전신마취 후 각막편재위치술, 각막편봉합술, 전방내공기주입술 등 응급 수술 진행하였음. 
수술 진행한 원장과 보호자 면담을 하였는데 사고를 인정하며 죄송하다 하였고 눈 관련하여 책임을 지겠다며 인정한 녹취기록을 가지고 있음.  의료사고 가 발생하고, 응급수술을 받고. 통원진료를 받은지도 10개월이 넘었음.  그동안 통원진료를 받은(의무기록지 및 진단서 발행하였음) 통원진료를 받은 10개월동안 치료를 받은게 아니고.  나빠지는걸 관찰하기위해 검사를 받은거였음. 
통원진료 하면서 각막혼탁 및 시력저하 난시가 심해졌다는 진단을 받았고. 시력회복 가능성은 희박하며 .각막 봉합으로 인한 수술 흉터 및 혼탁은 지워지지 않는다는 진단을 받았음. 
각막 혼탁도 지금은 커지지 않고 있으나 지속적으로 관찰하여 혼탁 진행여부를 봐야 하는 상태라고 함. 9개월 동안 통원진료를 받은 의무기록지를 의료사고를 낸 안과 원장과 같이 보며. 의논을 했음.  치료법이 있는데 그 치료법을 잘아는 병원에 가서 검사를 받아볼것을 권유하였고.
그 병원에 가서 검사를 받았음. 원추각막(각막확장증) 이라는 진단을 받았음.
(질문사항)
1. 의료사고로 인해 일을 하지못하는 상황이며.지금까지 완벽히 회복이 되지 않아 
일을 못하고 있는 상태입니다. 이럴 때 경력단절로 인한 피해보상을 받을 수 있을지 궁금합니다.
2. 지금까지 나온 병원비와 앞으로 남은 수술비는 사고를 낸 원장이 지불할 예정이지만 피해보상 관련하여 요구할 수 있는게 있을지 궁금합니다.
3.위에 질문에 해당하는 피해보상 관련한 비용이 있다면 합의금+피해보상 등 요구할 수 있는 대략적인 금액이 궁금합니다.'''

law_pre = preprocess(lawtalk)

In [ ]:
lawtalk2 = '''의료사고, 무면허의료행위
분당에 위치한 피부과 성형외과에서 실장들이 진단, 시술하여
얼굴 전체가 벗겨지고 화상을 입어 얼굴전체에 붉은 흉터가 생겼습니다. 통증도 생겼고 250 만원 지출.
경찰, 검찰에 신고 했고 돈과 치료비를 돌려받고 싶어요.
무면허 의료행위 
병원에서 위협가했고 삼성서울병원, 서울아산병원에서
마이신, 항생제 종류 수십알 복용해 위막성 대장염 생겼고
수술비 2,000 만원 나왔습니다.'''

law_pre2 = preprocess(lawtalk)

In [ ]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 3.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 44.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 60.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 21.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 45.5 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=fc9c83070a1b761c3cf34f90011be77035acda3fbd4c938e61b4d979ad10fd5a
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence-transformers


Input data

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

#Our sentences we like to encode
sentences = [law_pre, law_pre2]

#Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("") #입력 문장에 대한 고정 크기의 벡터

Sentence: ['안과 라식수술중 의료사고 입니다 ', ' 안과에서 시력교정수술 진행 가능한지 관련하여 검사를 받고 ', ' 수술가능하다는 소견을받고 라식수술진행 오른쪽 눈부터 수술하였으며 각막 절삭 중 각막을 깊게 자르는 의료사고 발생하였고 각막열공이 되어 ', '수술을 진행하던 원장님이 바로 수술 중단 후 대학 병원으로 이송하여 전신마취 후 각막편재위치술 각막편봉합술 전방내공기주입술 등 응급 수술 진행하였음 ', ' 수술 진행한 원장과 보호자 면담을 하였는데 사고를 인정하며 죄송하다 하였고 눈 관련하여 책임을 지겠다며 인정한 녹취기록을 가지고 있음 ', ' 의료사고 발생하고 응급수술을 받고 ', ' 통원진료를 받은지도 개월이 넘었음 ', ' 그동안 통원진료를 받은 통원진료를 받은 개월동안 치료를 받은게 아니고 ', ' 나빠지는걸 관찰하기위해 검사를 받은거였음 ', ' 통원진료 하면서 각막혼탁 및 시력저하 난시가 심해졌다는 진단을 받았고 ', ' 시력회복 가능성은 희박하며 ', '각막 봉합으로 인한 수술 흉터 및 혼탁은 지워지지 않는다는 진단을 받았음 ', ' 각막 혼탁도 지금은 커지지 않고 있으나 지속적으로 관찰하여 혼탁 진행여부를 봐야 하는 상태라고 함 ', ' 개월 동안 통원진료를 받은 의무기록지를 의료사고를 낸 안과 원장과 같이 보며 ', ' 의논을 했음 ', ' 치료법이 있는데 그 치료법을 잘아는 병원에 가서 검사를 받아볼것을 권유하였고 ', ' 그 병원에 가서 검사를 받았음 ', ' 원추각막 이라는 진단을 받았음 ', ' 의료사고로 인해 일을 하지못하는 상황이며 ', '지금까지 완벽히 회복이 되지 않아 일을 못하고 있는 상태입니다 ', ' 이럴 때 경력단절로 인한 피해보상을 받을 수 있을지 궁금합니다 ', ' 지금까지 나온 병원비와 앞으로 남은 수술비는 사고를 낸 원장이 지불할 예정이지만 피해보상 관련하여 요구할 수 있는게 있을지 궁금합니다 ', ' 위에 질문에 해당하는 피해보상 관련한 비용이 있다면 합의금 피해보상 등 요구할 수 있는 대략적인

In [ ]:
df

이유  \
0     \n  상고이유를 판단한다.\n  1. 이 사건 공소사실 중 2013. 9. 14....   
1     \n1. 항소이유의 요지\n  가. 법리오해(2014고단3764, 2014고단467...   
2     \n  상고이유를 판단한다.\n 형사소송법 제361조의3, 제364조 등의 규정에 ...   
3     \n     1. 항소이유의 요지\n     피고인은 이성 친구와 같이 있다가 별거...   
4     \n  상고이유를 판단한다.\n  1. 2015. 8. 4.자 상고이유서의 상고이유...   
...                                                 ...   
1595  \n1. 항소이유의 요지\n  원심의 형(징역 2년 6월)이 너무 무거워서 부당하다...   
1596  \n  상고이유를 판단한다.\n  원심판결 이유를 원심이  적법하게 채택한 증거들에...   
1597  \n범 죄 사 실\n[범죄전력]\n  피고인은 2013.  12.  3.  서울동부...   
1598  \n상고이유를 본다.\n\n본래 범의를 가지지 아니한 자에 대하여 수사기관이 사술이...   
1599  \n범 죄 사 실\n 피고인 A는 경기도 의정부시 고산동에 있는 캠프 스탠리에서 복...   

                                                  참조 조문  \
0                               형법 제331조 제2항, 제347조 제1항   
1                                               no data   
2                                  형사소송법 제361조의3, 제364조   
3     [1] 형법 제347조 / [2] 형법 제347조 제1항, 제352조, 상법 제73...   
4                [1] 형법 제246조 제1항, 제347조 / [2] 형법 제347조   
...                                                 ...   
1595                                            no data   
1596                                            no data   
1597                                            no data   
1598  [1] \n        형법 제13조 / [2] \n        형법 제13조\...   
1599                                            no data   

                                                     요지  \
0     피고인 등이 피해자 갑 등에게 자동차를 매도하겠다고 거짓말하고 자동차를 양도하면서 ...   
1                                               no data   
2      형사소송법 제361조의3, 제364조 등의 규정에 의하면 항소심의 구조는 피고인 ...   
3     \n   [1] 사기죄는 타인을 기망하여 착오에 빠뜨리고 처분행위를 유발하여 재물을...   
4                                               no data   
...                                                 ...   
1595                                            no data   
1596                                            no data   
1597                                            no data   
1598                                            no data   
1599                                            no data   

                                                  참조 판례  
0                                                nodata  
1                                                nodata  
2      대법원 2004. 6. 25. 선고 2004도2611 판결(공2004하, 1295...  
3     [1]대법원 2009. 9. 10. 선고 2009다30762 판결(공2009하, 1...  
4     [1] 대법원 2011. 1. 13. 선고 2010도9330 판결(공2011상, 3...  
...                                                 ...  
1595                                             nodata  
1596                                             nodata  
1597                                             nodata  
1598  [1] \n        대법원 2007. 7. 12. 선고 2006도2339 판결...  
1599                                             nodata  

[1600 rows x 4 columns]

In [ ]:
df['sen_list']

KeyError: ignored

In [ ]:
from sentence_transformers import SentenceTransformer, util
# model = SentenceTransformer('all-MiniLM-L6-v2')

# Two lists of sentences
sentences1 = [law_pre]#, law_pre2]
# sentences2 = []
cosine_list = []

embeddings1 = model.encode(sentences1, convert_to_tensor=True)

for i in range(len(df['전처리'])):
  embeddings2 = model.encode(df['전처리'][i], convert_to_tensor=True)

  cosine_list.append(util.cos_sim(embeddings1, embeddings2)[0])
  # break
# df['mean'] = cosine_list.apply(lambda x : sum(x)/len(x))
# df['max']

  
# #Compute embedding for both lists
# # embeddings1 = model.encode(sentences1, convert_to_tensor=True)
# # embeddings2 = model.encode(sentences2, convert_to_tensor=True)

# #Compute cosine-similarities
# # cosine_scores = util.cos_sim(embeddings1, embeddings2)

# #Output the pairs with their score
# for i in range(len(sentences1)):
#     print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i], sentences2[i], cosine_scores[i][i]))

KeyError: ignored

In [ ]:
cosine_list

[tensor([0.8925]),
 tensor([0.8434]),
 tensor([0.8556]),
 tensor([0.8706]),
 tensor([0.8121]),
 tensor([0.8959]),
 tensor([0.9235]),
 tensor([0.9123]),
 tensor([0.8874]),
 tensor([0.7946]),
 tensor([0.8649]),
 tensor([0.8653]),
 tensor([0.8936]),
 tensor([0.8113]),
 tensor([0.8544]),
 tensor([0.9449]),
 tensor([0.8729]),
 tensor([0.9010]),
 tensor([0.8239]),
 tensor([0.9210]),
 tensor([0.8530]),
 tensor([0.9015]),
 tensor([0.9028]),
 tensor([0.7579]),
 tensor([0.7616]),
 tensor([0.8177]),
 tensor([0.8619]),
 tensor([0.8955]),
 tensor([0.9418]),
 tensor([0.8810]),
 tensor([0.8373]),
 tensor([0.8470]),
 tensor([0.8857]),
 tensor([0.8921]),
 tensor([0.8354]),
 tensor([0.8416]),
 tensor([0.8285]),
 tensor([0.8633]),
 tensor([0.8260]),
 tensor([0.9178]),
 tensor([0.8863]),
 tensor([0.9000]),
 tensor([0.8187]),
 tensor([0.8242]),
 tensor([0.9449]),
 tensor([0.8514]),
 tensor([0.8239]),
 tensor([0.9248]),
 tensor([0.9150]),
 tensor([0.8852]),
 tensor([0.8974]),
 tensor([0.8153]),
 tensor([0.9

In [ ]:
df['cos'] = cosine_list

In [ ]:
df['cos']

0      [tensor(0.8925)]
1      [tensor(0.8434)]
2      [tensor(0.8556)]
3      [tensor(0.8706)]
4      [tensor(0.8121)]
             ...       
195    [tensor(0.9053)]
196    [tensor(0.7044)]
197    [tensor(0.9114)]
198    [tensor(0.8400)]
199    [tensor(0.9233)]
Name: cos, Length: 200, dtype: object

In [ ]:
df['cos'].iloc[0].numpy()[0]

0.8925382

In [ ]:
df['cos'] = df['cos'].apply(lambda x : x.numpy()[0])

In [ ]:
idx = df['cos'].argmax()

In [ ]:
display(f'의뢰사연: {law_pre}')
print(f'유사한 판결문 번호: {idx}')
# print(f'유사한 판결문 원본: {pan}')

'의뢰사연: 안과 라식수술중 의료사고 입니다 . 안과에서 시력교정수술 진행 가능한지 관련하여 검사를 받고 . 수술가능하다는 소견을받고 라식수술진행 오른쪽 눈부터 수술하였으며 각막 절삭 중 각막을 깊게 자르는 의료사고 발생하였고 각막열공이 되어 .수술을 진행하던 원장님이 바로 수술 중단 후 대학 병원으로 이송하여 전신마취 후 각막편재위치술 각막편봉합술 전방내공기주입술 등 응급 수술 진행하였음 . 수술 진행한 원장과 보호자 면담을 하였는데 사고를 인정하며 죄송하다 하였고 눈 관련하여 책임을 지겠다며 인정한 녹취기록을 가지고 있음 . 의료사고 발생하고 응급수술을 받고 . 통원진료를 받은지도 개월이 넘었음 . 그동안 통원진료를 받은 통원진료를 받은 개월동안 치료를 받은게 아니고 . 나빠지는걸 관찰하기위해 검사를 받은거였음 . 통원진료 하면서 각막혼탁 및 시력저하 난시가 심해졌다는 진단을 받았고 . 시력회복 가능성은 희박하며 .각막 봉합으로 인한 수술 흉터 및 혼탁은 지워지지 않는다는 진단을 받았음 . 각막 혼탁도 지금은 커지지 않고 있으나 지속적으로 관찰하여 혼탁 진행여부를 봐야 하는 상태라고 함 . 개월 동안 통원진료를 받은 의무기록지를 의료사고를 낸 안과 원장과 같이 보며 . 의논을 했음 . 치료법이 있는데 그 치료법을 잘아는 병원에 가서 검사를 받아볼것을 권유하였고 . 그 병원에 가서 검사를 받았음 . 원추각막 이라는 진단을 받았음 . 의료사고로 인해 일을 하지못하는 상황이며 .지금까지 완벽히 회복이 되지 않아 일을 못하고 있는 상태입니다 . 이럴 때 경력단절로 인한 피해보상을 받을 수 있을지 궁금합니다 . 지금까지 나온 병원비와 앞으로 남은 수술비는 사고를 낸 원장이 지불할 예정이지만 피해보상 관련하여 요구할 수 있는게 있을지 궁금합니다 . 위에 질문에 해당하는 피해보상 관련한 비용이 있다면 합의금 피해보상 등 요구할 수 있는 대략적인 금액이 궁금합니다 .'

유사한 판결문 번호: 105


In [ ]:
df['전처리'][105]

' 진단 및 수술 경과 원고는 경부터 양측 하지에 저린 감각 증상이 발생하였고 경부터 양측 하지 저린감과 통증이 악화되었다 . 원고는 양측 하지의 근위약이 동반된 상태에서 허리 및 하지 통증 하지 허약감 및 저린 증상 좌측 하지 감각 이상 보행 장애 배뇨 및 배변 곤란 등을 주소로 피고가 운영하는 병원에 처음 내원하였다 . 원고에 대해 시행한 검사 결과 흉추 번 중증의 척추관협착 및 중심성 돌출 추간판 탈출 흉추 번 후종인대골화증 경미한 척추관 협착 및 압박성 척수증 동반한 흉추 번 황색인대골화증의 소견이 나왔다 . 원고에 대해 시행한 흉추 차원 컴퓨터 단층촬영 검사 결과 흉추 번 흉추 번 중증의 척추관 협착을 동반한 후종인대골화증 흉추 번 척추관 협착을 동반한 황색인대골화증 흉추 번 미만성 특발성 골격 과골증의 소견이 나왔다 . 피고 병원 의료진은 원고에 대한 검사 결과와 임상을 토대로 주진단은 흉추 번 번 후종인대골화증 기타 진단명 경추 번 후종인대골화증 흉추 번 번 황색인대석회화의 진단을 하였다 . 원고는 피고 병원에 입원하여 경부터 경까지 피고 병원 의료진으로부터 흉추 번 흉강경 가이드하 척추 융합술 및 자가골 이식술을 시행받았다 . 수술 직후 원고에게 심한 하지 통증 및 하지 마비 등의 증상이 발생하자 피고 병원 의료진은 경 흉추 차원 컴퓨터 단층촬영 검사를 하였는데 피고 병원 영상의학과 의사는 위 검사 결과에서 흉추 번 후종인대골화증으로 수술후 상태로 흉추 번 추간판 층에 케이지가 삽입되어 있고 이전 컴퓨터 단층촬영에서 관찰되는 흉추 번 흉추 번 후종인대골화증 흉추 번 황색인대골화증 흉추 번 미만성 특발성 골격 과골증은 이전과 큰 차이가 없다 는 소견을 보였다 . 피고 병원 의료진은 경부터 경까지 원고에게 흉추 번 흉강경 가이드하 척추 융합술 및 자가골 이식술을 시행하였다 . 수술 후에도 원고의 위 하지 마비 등의 증상은 소멸하지 않았고 원고는 피고 병원에서 퇴원하였다 . 원고의 상태 원고는 피고 병원에 내원하여 시행한 도수근력검사 에서 근력 등급이